Ex 4

In [ ]:
"""
Exercise 4: NumPy Array Operations
Complete the following tasks using NumPy.
"""

In [3]:
import numpy as np
rows,cols=5,5
arr = np.ones((rows,cols))
arr[:,:]=0
arr[:,-1]=1
arr[0,:]=1
arr[-1,:]=1
arr[:,0]=1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
#Task 2:
# TODO: Normalize each column to have mean=0 and std=1
np.random.seed(42)
random_data = np.random.randn(100, 3)
col1=[]
col2=[]
col3=[]
col1=random_data[:,0]
col2=random_data[:,1]
col3=random_data[:,2]
normal_datacol1 = (col1 - col1.mean())/col1.std()
normal_datacol2 = (col2 - col2.mean())/col2.std()
normal_datacol3 = (col3 - col3.mean())/col3.std()
print(normal_datacol1)
print(normal_datacol2)
print(normal_datacol3)

[ 4.93439239e-01  1.74402998e+00  1.81249029e+00  5.49303576e-01
  1.83017852e-01 -7.96980164e-01 -1.21826859e+00 -3.86933017e-01
 -7.75162723e-01  3.45978124e-01 -8.45013279e-01 -1.40066567e+00
  1.42686307e-01  1.28061139e-01 -2.52739338e-01 -9.88966824e-01
  3.06888192e-01 -5.81051242e-01  1.14447901e+00 -4.88601912e-01
 -6.95704590e-01 -1.56942606e+00 -1.99565174e-01 -8.97913253e-01
 -1.55473986e-01  8.89689184e-01 -6.33645019e-06  3.23331304e-01
 -1.09698828e+00  2.88772170e-01  6.47228102e-03 -5.11083408e-01
  2.49010704e-01 -3.97669232e-01 -5.29425088e-01  3.80526750e-01
  2.02012356e-01 -1.44126887e-01 -3.46215614e-01 -1.53588180e+00
  8.52072656e-01 -1.82000883e+00 -1.31881178e+00 -7.25316459e-01
 -1.40626209e+00  1.77681383e+00  8.79471507e-01  1.48096627e+00
  2.04854446e-01 -1.72082770e+00  1.93412571e-01  1.71187717e-01
  2.16167271e+00  6.88207518e-01  1.29995791e+00  3.91164554e-01
 -4.10830493e-01 -1.10590383e+00  2.25335411e-01  1.65934768e+00
  6.50571855e-01  4.76085

In [20]:
# Task 3: Implement linear regression solution using normal equation
# (10 points)
# Given X (features) and y (target), compute theta
# theta = (X^T X)^(-1) X^T y
X = np.random.randn(50, 3)
true_theta = np.array([2.5, -1.2, 3.7])
y = X @ true_theta + np.random.randn(50) * 0.1
# TODO: Calculate theta_hat using the normal equation

col1=[]
col2=[]
col3=[]
col1=random_data[:,0]
col2=random_data[:,1]
col3=random_data[:,2]
normal_datacol1 = (col1 - col1.mean())/col1.std()
normal_datacol2 = (col2 - col2.mean())/col2.std()
normal_datacol3 = (col3 - col3.mean())/col3.std()
print(normal_datacol1)
print(normal_datacol2)
print(normal_datacol3)
# TODO: Print the estimated coefficients and compare with true_theta

EX 5

In [28]:
"""
Exercise 5: Pandas Data Analysis
Analyze a dataset of student performance.
"""

import pandas as pd
import numpy as np

# Create sample dataset
np.random.seed(42)
n_students = 200

data = {
    'student_id': range(1000, 1000 + n_students),
    'major': np.random.choice(['CS', 'Math'
        , 'Physics', 'Biology'], n_students),
    'year': np.random.choice([1, 2, 3, 4], n_students),
    'exam_score': np.random.normal(75, 10, n_students).clip(0, 100),
    'assignments_completed': np.random.randint(0, 11, n_students),
    'hours_studied': np.random.normal(15, 5, n_students).clip(1, 40)
}

df = pd.DataFrame(data)

# Introduce some NaN values
df.loc[np.random.choice(n_students, 10), 'exam_score'] = np.nan
df.loc[np.random.choice(n_students, 5), 'hours_studied'] = np.nan

In [33]:
#Ex 5
# Task 1: Data Cleaning and Exploration (10 points)
# TODO: Display basic information about the dataset
print(df.info())
# TODO: Identify and count missing values
print(df.isnull().sum())
# TODO: Fill missing exam_score with the mean score for the student's major
df["exam_score"]=df.groupby("major")["exam_score"].df["exam_score"].fillna(df["exam_score"].mean())


# TODO: Fill missing hours_studied with the median for the student's year
df["hours_studied"]=df.groupby("year")["hours_studied"].df.fillna(df.median())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   student_id             200 non-null    int64  
 1   major                  200 non-null    object 
 2   year                   200 non-null    int64  
 3   exam_score             190 non-null    float64
 4   assignments_completed  200 non-null    int64  
 5   hours_studied          195 non-null    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 9.5+ KB
None


,0
student_id,0
major,0
year,0
exam_score,10
assignments_completed,0
hours_studied,5


In [ ]:
# Task 2: Analysis (10 points)
# TODO: Calculate and display the average exam_score by major
print(df.groupby("major"["exam_score"].mean()))
# TODO: Find the major with the highest average exam_score
high_scorers = df[df['Score'] > 90]
# TODO: Calculate the correlation between hours_studied and exam_score
# TODO: Create a new column 'performance' with categories:
#       'Excellent' (>90), 'Good' (80-90), 'Average' (70-80), 'Needs Improvement' (<70)

In [ ]:
# Task 3: Advanced Analysis (10 points)
# TODO: For each major and year combination, calculate:
#       - Number of students
count=0
for value in df["student_id"]:
  count+=1;
print(count)
#       - Average exam score
exam_av=0
exam_tot=0
for value in df["exam_score"]:
  exam_tot+=value
exam_av=exam_tot/count
print(exam_av)

#       - Average hours studied
hours_av=0
hours_tot=0
for value in df["hours_studied"]:
  hours_tot+=value
hours_av=hours_tot/count
print(hours_av)

# TODO: Identify top 5 students based on exam_score (handle ties appropriately)
c=0
top_stu = df["hours_studied"].sort_values('Score', ascending=False)
for value in df["hours_studied"]:
  if c<5:
    c+=1
    print(hours_av)
# TODO: Create a pivot table showing average exam_score by major (rows) and year (columns)
exam_pivot = df.pivot_table(values="exam_score",index="major",columns="year",aggfunc="mean")
print(exam_pivot)

Ex 6

In [ ]:
"""
Exercise 6: Data Visualization
Create meaningful visualizations using the dataset from Exercise 5.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Continue using the df from Exercise 5

# Task 1: Distribution Visualization (8 points)
# TODO: Create a figure with 2 subplots side by side
#       Left: Histogram of exam scores with KDE overlay
#       Right: Box plot of exam scores by major
# TODO: Add appropriate titles, labels, and styling

# Task 2: Relationship Visualization (8 points)
# TODO: Create a scatter plot of hours_studied vs exam_score
# TODO: Color points by major
# TODO: Add a regression line
# TODO: Include appropriate legends, titles, and axis labels

# Task 3: Advanced Dashboard (9 points)
# TODO: Create a 2x2 subplot figure containing:
#       1. Bar chart: Average exam score by major
#       2. Count plot: Number of students by year
#       3. Heat map: Correlation matrix of numerical columns
#       4. Violin plot: Exam score distribution by performance category
# TODO: Adjust layout, add titles, and ensure readability

Ex 7

In [ ]:
"""
Exercise 7: Integration Challenge
Combine NumPy, Pandas, and Matplotlib to solve a mini data science problem.
"""

# Scenario: You're analyzing customer data for an e-commerce company.
# Generate synthetic data and provide insights.

np.random.seed(42)
n_customers = 500

# Generate customer data
ages = np.random.randint(18, 70, n_customers)
income = np.random.normal(50000, 20000, n_customers).clip(15000, 150000)
purchase_freq = np.random.poisson(5, n_customers)
avg_purchase_value = np.random.normal(100, 30, n_customers).clip(10, 500)

# Create DataFrame
customers = pd.DataFrame({
    'age': ages,
    'income': income,
    'purchase_frequency': purchase_freq,
    'avg_purchase_value': avg_purchase_value
})

# TODO: Calculate customer lifetime value (CLV)
#       CLV = purchase_frequency * avg_purchase_value * (1 + churn_risk)
#       where churn_risk = 1 - (purchase_frequency / max_frequency)

# TODO: Create age groups: 18-25, 26-35, 36-50, 51-70

# TODO: For each age group, calculate:
#       - Number of customers
#       - Average income
#       - Average CLV
#       - Total CLV

# TODO: Identify top 10% of customers by CLV

# TODO: Create visualizations:
#       1. Scatter plot of income vs CLV (color by age group)
#       2. Bar chart of average CLV by age group
#       3. Correlation heatmap

# TODO: Write a brief analysis paragraph (as a markdown cell)
#       summarizing key findings and recommendations